bmstu_lb: Добавление провайдера сети МГТУ им. Баумана
mosmetro-android/mosmetro-android pull request #242
Opened 2021-09-11 13:47 UTC by Alesha72003

Делал по образу и подобию маёвской сети. Получившийся результат проверил - работает

2021-09-11 14:35 UTC, TheDrHax requested changes
Всё круто! Но есть пара мелочей

2021-09-11 14:35 UTC, TheDrHax commented on app/src/main/res/xml/pref_conn.xml
> +        android:summary="@string/pref_bmstu_lb"
Здесь должен быть ключ `pref_bmstu_lb_summary`, иначе название и описание опции совпадают.

2021-09-11 14:35 UTC, TheDrHax commented on app/src/main/java/pw/thedrhax/mosmetro/authenticator/providers/bmstu_lb.java
> +                    HttpResponse response = client.post(redirect, "redirurl=&auth_user=" + login + "&auth_pass=" + password + "&accept=Continue", "application/x-www-form-urlencoded").retry().execute(
Вместо ручного составления тела запроса лучше воспользоваться методом `Client.post(String link, Map<String,String> form)`. Вскорее всего в данном случае это не критично, но этот метод правильно экранирует особые символы в запросе, если они есть.

```
HttpResponse response = client.post(redirect, new HashMap<String,String>() {{
    put("redirurl", "");
    put("auth_user", login);
    put("auth_pass", password);
    put("accept", "Continue");
}}).retry().execute();
```

В MAInet тоже так форма отправляется: https://github.com/mosmetro-android/mosmetro-android/blob/e46f813b587d05422a755b02a377e8ac422d99fc/app/src/main/java/pw/thedrhax/mosmetro/authenticator/providers/MAInet.java#L90-L100

2021-09-11 14:35 UTC, TheDrHax commented on app/src/main/java/pw/thedrhax/mosmetro/authenticator/providers/bmstu_lb.java
> +public class bmstu_lb extends Provider {
Названия классов обычно начинаются с большой буквы и не используют специальных символов. Может просто в `Bmstu` переименовать?

2021-09-11 21:25 UTC, Alesha72003 commented on app/src/main/java/pw/thedrhax/mosmetro/authenticator/providers/bmstu_lb.java
> +                    HttpResponse response = client.post(redirect, "redirurl=&auth_user=" + login + "&auth_pass=" + password + "&accept=Continue", "application/x-www-form-urlencoded").retry().execute(
Я пытался сделать так, но возникала неизвестная ошибка на сервере. Пока что работает так. Короче говоря, этот вопрос требует дальнейшего тестирования

2021-09-11 21:29 UTC, Alesha72003 commented on app/src/main/java/pw/thedrhax/mosmetro/authenticator/providers/bmstu_lb.java
> +                    HttpResponse response = client.post(redirect, "redirurl=&auth_user=" + login + "&auth_pass=" + password + "&accept=Continue", "application/x-www-form-urlencoded").retry().execute(
Сообственно, поэтому и пришлось сделать коммит `bmstu_lb: fix auth`. Видимо как раз особое экранирование адреса ломало сервер. Надо будет попробовать с пустым адресом.

2021-09-12 12:08 UTC, TheDrHax commented on app/src/main/java/pw/thedrhax/mosmetro/authenticator/providers/bmstu_lb.java
> +                    HttpResponse response = client.post(redirect, "redirurl=&auth_user=" + login + "&auth_pass=" + password + "&accept=Continue", "application/x-www-form-urlencoded").retry().execute(
А, я, кажется, понял, в чём проблема. Метод преобразования HashMap в строку добавляет `?` в начало, т.к. он всегда использовался с GET-запросами. Хотя непонятно, как оно в МАИ работает :)

Тогда лучше оставить, да. Я попробую потом исправить клиент.

2021-09-12 12:08 UTC, TheDrHax approved these changes

2021-09-12 12:18 UTC, merged